### ISSUE TITLE
How to use with nested properties of store

### ISSUE THREAD

**Issue by neeravp** [cklmercer/vue-stash#1]
In your example the store object doesn't have any nested properties. If the store has nested properties like:    

```
store:{   

     user:{  
           name:'',  
           address:{  
                block:'',
                street:'',
                city:''
           },
           role:'',
           department:{
                 name:'',
                 division:{
                       name:'',
                       subDivision:{
                            name:'',
                            projects:[{team:'', leader:'', 'type:''}]
                       }
                  }
           }
   }  
}
```

Then how do you write the get and set function of the Store Accessor?

**Comment by cklmercer** [comment]
So, the easiest option is just to do something like `store: ['user']`, and then you can access all the nested props off of the users e.g. `this.user.department.division.subDivision.name`.

I have considered extending the plugin so that you can define a local name and store path. Haven't thought it through that much, but the API could be something like 

```
store: {
    subDivisionName: 'this.user.department.division.subDivision.name'
}
```

This would allow you to get/set the the nested prop with `this.subDivisionName`.

What do you think? Is the above something like what you're looking for?

**Comment by neeravp** [comment]
Yes exactly that is what I am looking for. Since mostly the nested (object) properties will be referring entities and would be represented by individual components like   

```
<user :user="user">  
    <input name="name">
    <address :address="user.address"></address>  
    <input name="role">  
    <department :department="user.department">  
         <input name="department-name">
         <division :division="department.division">  
               <input name="division-name">  
               <sub-division :subDivision="division.subDivision">  
                     <input name="sub-division-name">  
                      <project v-for="project in subDivision.projects">
                </sub-division>  
          </division>  
     </department>  
</user>  
```

So being able to get the nested properties within components and being able to perform crud operations is what I am looking for.  
Thanks for responding back.

**Comment by cklmercer** [comment]
Pushed an update today to allow for this. Please see updated readme.

**Comment by neeravp** [comment]
Thanks for the update.  
I still have one doubt though, if the store has nested properties with arrays of objects, how do I set / update the store value from such a component.  
For instance instance in my user store above, if there are two or three projects that the user is involved in, the update forms would be represented by multiple `<project>` components, get part of the store value is easier because while rendering the component the data tree will be traversed from top to bottom so for views I can have:  

```
<project v-for="project in project">  
// And in project component I can get the value through the prop    
 //But if I want to directly access each project property from the store in the component  
//It would be something like:  
Vue.component('project', {
    store:{
        project:'user.department.division.subDivision.projects[0]'  
    }  
}  
// How to provide the index of the projects array within the key?  
//Would the below work:  
Vue.component('project', {  
    data(){  
        return{  
            id:1  
        }  
    }
    store:{  
        project(){
            let projects = 'user.department.dvision.subDivision.projects',
                 activeProject = {};  
                 projects.forEach( p => {
                      if(p.id == this.id){
                            activeProject = p;  
                      }  
                 }  
                 return activeProject;  
        }
    }
```

**Comment by cklmercer** [comment]
So, when it comes to accessing a specific index you'll still want to use dot notation, like `user.department.division.subDivision.projects.0`.

Unfortunately, you can't access data from your data option from within your store option. Reason being is that the data option hasn't yet finished being initialized whenever we setup the store. For this your best option is using a computed property. Something like the following should work nicely.

```
data() {
    return {
       id: '1'
    }
},

store: {
    projects: 'user.department.division.subDivision.projects'
},

computed: {
    activeProject: {
        get() {
            return this.projects[this.id];
        },
        set(project) {
            this.projects[this.id] = project;
        }
    }
}
```

Not the most elegant solution, but it'll work until I figure out something better.

**Comment by neeravp** [comment]
Sorry for the delayed response, and thanks for the response. Am travelling, so might not be able to try out soon. Will post my experience after I try out.  Thanks again.
