### ISSUE TITLE
Call an api from store

### ISSUE THREAD

**Issue by ServerJunge** [cklmercer/vue-stash#12]
Hi,

is it possible to make an api call from store? I would like to call an endpoint when the store is created. 

My store.js

export default {
    user: {
        name: null
    }
}

**Comment by cklmercer** [comment]
`vue-stash` doesn't include any hooks. With that in mind, you can always hook into the `created` life-cycle hook. The store is initialized during the `beforeCreate` life-cycle hook, so once `created` rolls around you can trust that your store is ready to go.

**Comment by ServerJunge** [comment]
Hmm... I want vue-stash to hold my user object wich I can get via an api call. But I don't know where I should call that api so that i can use the stored data in my different components

**Comment by cklmercer** [comment]
maybe this example will give you a better idea. If the example below isn't appealing, then it could be that you need something for full-featured, like `vuex`.

https://gist.github.com/cklmercer/096137d96986e2ecfba3d244e6f1f8ce

**Comment by ServerJunge** [comment]
When I try 

console.log(this.$store.user.name)

I get

Uncaught TypeError: Cannot read property 'user' of undefined

I try to check for the user before routing for example

import store from './store'

console.log(store.user.name);

router.beforeEach((to, from, next) => {
    console.log('Router Before each')
    next();
})

->>> console output: null

**Comment by cklmercer** [comment]
So, I was finally able to reproduce this issue. Are you using the latest version of `vue` by chance? I think the bug might have been introduced with some of the new changes. I'm working on a proper solution now.

**Comment by cklmercer** [comment]
So, the issue I was able to reproduce appears to have been unrelated :(
