### ISSUE TITLE
how to access the store from plain javascript outside vue?

### ISSUE THREAD

**Issue by unitedworx** [cklmercer/vue-stash#13]
How can I access the store from plain javascript outside vue?

I want to unitize the store to make sure my vue components reach to outside changes done in plain old jquery.

**Comment by unitedworx** [comment]
i figured i can do window.app.$store to acess the store from anywhere!

**Comment by cklmercer** [comment]
`vue-stash` doesn't provide anything to make this easier. That said, what you mentioned is probably the simplest solution.
