### ISSUE TITLE
Computed store properties?

### ISSUE THREAD

**Issue by psi-4ward** [cklmercer/vue-stash#14]
Hi,

is it possible to use computed properties with vue-stash? 

like
```
store: {
  val1: true
  $computed: {
     derived: function() { return this.$store.val1 ? 'yes' : 'no' }
  }
}
```

**Comment by cklmercer** [comment]
Absolutely. The properties in your store actually get loaded into your components as computed properties, so you're essentially just creating one computed property from another.

Sorry about the slow reply!

**Comment by psi-4ward** [comment]
Can u draft a code sample pls?

**Comment by cklmercer** [comment]
vue stash doesn't have any built in way to handle computed properties. What you'd probably want to do is use a mixin with a standard computed property. That way you can easily share that data between components. I might look into adding this feature down the road, but for right now I'd like to keep this plugin dirt simple.
