### ISSUE TITLE
What is the purpose of the Dynamic store access?

### ISSUE THREAD

**Issue by zatziky** [cklmercer/vue-stash#20]
Hi there,

I will just repeat my question. :) What is the purpose of the Dynamic store access?

Thank you for your answer!

Nobo

**Comment by cklmercer** [comment]
It allows you to use javascript to change the data that you retrieve from the store. I added it because I needed it when I was working a data table component.

**Comment by zatziky** [comment]
Thank you @cklmercer  but I still don't understand how you would change the data when you're using a string? In the example the string 'user.name':

```
store: {
        name() {
            return 'user.name';
        }
    },
```

**Comment by cklmercer** [comment]
That's a very naive example, which I should update. In reality you might do something more like this..

```
store: {
  userId() {
    return someConditional ? 'user.username' : 'user.email';
  }
}
```

**Comment by zatziky** [comment]
Oh my, I can see now!
