### ISSUE TITLE
Using functions inside the store

### ISSUE THREAD

**Issue by KINKCreative** [cklmercer/vue-stash#25]
Wondering if this breaks some convention or is a big no no for some reason.

I have been able to create nested methods instide a store property e.g.

```
store: {
   messages: {
       list: [],
       setMessage(message) {
          this.list.push(message)
       }
   }
...
}
```

Can you share some insight if this is going to make the computer explode? :)

**Comment by danikane** [comment]
Well, I have methods in my store as well. :) Haven't had any hiccups yet.
