### ISSUE TITLE
Can't push to array

### ISSUE THREAD

**Issue by sujeshthekkepatt** [cklmercer/vue-stash#26]
Initialized the store with an array. When I push some data and after reloading the page the data not saved. Any help ???  BTW really a great lib.

**Comment by danikane** [comment]
I've neved had any troubles with any kind of data. Vue wraps arrays and array methods really nice.
Can you share some part of the code please? 
Also what do you mean by "reload the page" ? 
https://vuejs.org/v2/guide/list.html#Array-Change-Detection
