### ISSUE TITLE
How to add hook for sets

### ISSUE THREAD

**Issue by xhh2a** [cklmercer/vue-stash#8]
First off, a big thanks for making this library. Really solves the simple use cases I want.

I would like to save to localStorage (debounced) every time something is updated (set is called). Do you have any insights on the best way to do so while using vue-stash? I'm not sure how I would go about extending/overriding the set() function in ```store-accessor.js``` after I import vue-stash and tell Vue to use it. Or would it require changing the file itself prior to importing and making a fork?

Thanks!

**Comment by xhh2a** [comment]
Nevermind I figured out how to do this using a global mixin method and having that handle all state updates.

**Comment by Leomund** [comment]
@xhh2a Hello. I have same case. Would you share your solution?

**Comment by Leomund** [comment]
@xhh2a I solved it with adding vue watcher on store in my App.vue component. But i still interested to see your solution.
