### ISSUE TITLE
Using it with Router

### ISSUE THREAD

**Issue by karneaud** [cklmercer/vue-stash#9]
Is there a way to use this in the VueRouter?

**Comment by cklmercer** [comment]
Sure thing. You can checkout https://GitHub.com/cklmercer/vue-stack-2.0 for
an example.

Is there something specific you're trying to do?

**Comment by karneaud** [comment]
@cklmercer 

I am trying to regulate Router routes based on the "store" state i.e.

I have a route
```
{ path: '/user', beforeenter: (to, form, next) => {
  if(router.store.user === role) next()
 else next('/')
}, component.....
```

**Comment by cklmercer** [comment]
The simplest solution in this scenario would be to import your store and treat it like the plain ole JS Object that it is.
